BEGIN;

ALTER TABLE legend_commerce.orders
  ADD COLUMN IF NOT EXISTS document_profile_version smallint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS order_number text,
  ADD COLUMN IF NOT EXISTS order_number_assigned_at bigint,
  ADD COLUMN IF NOT EXISTS invoice_id bigint;

ALTER TABLE legend_commerce.orders
  ADD CONSTRAINT orders_document_profile_version_allowed
    CHECK (document_profile_version IN (0, 1)),
  ADD CONSTRAINT orders_order_number_nonempty
    CHECK (order_number IS NULL OR char_length(btrim(order_number)) > 0),
  ADD CONSTRAINT orders_order_number_assigned_at_nonnegative
    CHECK (order_number_assigned_at IS NULL OR order_number_assigned_at >= 0),
  ADD CONSTRAINT orders_v3_document_identity_complete
    CHECK (
      document_profile_version = 0
      OR (
        (
          status = 'paid'
          AND paid_at IS NOT NULL
          AND order_number IS NOT NULL
          AND order_number_assigned_at IS NOT NULL
          AND invoice_id IS NOT NULL
        )
        OR (
          status <> 'paid'
          AND order_number IS NULL
          AND order_number_assigned_at IS NULL
          AND invoice_id IS NULL
        )
      )
    );

CREATE UNIQUE INDEX IF NOT EXISTS orders_order_number_uidx
  ON legend_commerce.orders (order_number)
  WHERE order_number IS NOT NULL;

ALTER TABLE legend_commerce.orders
  ADD CONSTRAINT orders_reference_order_number_unique
    UNIQUE (reference, order_number);

CREATE TABLE IF NOT EXISTS legend_commerce.document_number_series (
  document_type text NOT NULL,
  series_key text NOT NULL,
  next_value bigint NOT NULL,
  updated_at bigint NOT NULL,

  CONSTRAINT document_number_series_pkey
    PRIMARY KEY (document_type, series_key),
  CONSTRAINT document_number_series_type_allowed
    CHECK (document_type IN ('order', 'invoice')),
  CONSTRAINT document_number_series_key_nonempty
    CHECK (char_length(btrim(series_key)) BETWEEN 1 AND 64),
  CONSTRAINT document_number_series_next_value_positive
    CHECK (next_value >= 1),
  CONSTRAINT document_number_series_updated_at_nonnegative
    CHECK (updated_at >= 0)
);

CREATE TABLE IF NOT EXISTS legend_commerce.invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_reference text NOT NULL,
  order_number text NOT NULL,
  invoice_number text NOT NULL,
  status text NOT NULL,
  issued_at bigint NOT NULL,
  currency text NOT NULL,
  amount_total integer NOT NULL,
  schema_version smallint NOT NULL,
  snapshot jsonb NOT NULL,
  created_at bigint NOT NULL,

  CONSTRAINT invoices_order_reference_fk
    FOREIGN KEY (order_reference)
    REFERENCES legend_commerce.orders(reference)
    ON DELETE RESTRICT,
  CONSTRAINT invoices_order_reference_unique
    UNIQUE (order_reference),
  CONSTRAINT invoices_order_number_unique
    UNIQUE (order_number),
  CONSTRAINT invoices_invoice_number_unique
    UNIQUE (invoice_number),
  CONSTRAINT invoices_id_order_reference_unique
    UNIQUE (id, order_reference),
  CONSTRAINT invoices_status_issued
    CHECK (status = 'issued'),
  CONSTRAINT invoices_order_number_nonempty
    CHECK (char_length(btrim(order_number)) > 0),
  CONSTRAINT invoices_invoice_number_nonempty
    CHECK (char_length(btrim(invoice_number)) > 0),
  CONSTRAINT invoices_timestamps_nonnegative
    CHECK (issued_at >= 0 AND created_at >= 0),
  CONSTRAINT invoices_currency_eur
    CHECK (currency = 'EUR'),
  CONSTRAINT invoices_amount_nonnegative
    CHECK (amount_total >= 0),
  CONSTRAINT invoices_schema_version_v1
    CHECK (schema_version = 1),
  CONSTRAINT invoices_snapshot_v1_object
    CHECK (
      jsonb_typeof(snapshot) = 'object'
      AND snapshot ->> 'schemaVersion' = '1'
    ),
  CONSTRAINT invoices_order_identity_fk
    FOREIGN KEY (order_reference, order_number)
    REFERENCES legend_commerce.orders(reference, order_number)
    DEFERRABLE INITIALLY DEFERRED
);

ALTER TABLE legend_commerce.orders
  ADD CONSTRAINT orders_invoice_same_order_fk
    FOREIGN KEY (invoice_id, reference)
    REFERENCES legend_commerce.invoices(id, order_reference)
    ON DELETE RESTRICT
    DEFERRABLE INITIALLY DEFERRED;

COMMENT ON COLUMN legend_commerce.orders.document_profile_version IS
  '0 preserves legacy/pre-V3 document behavior; 1 requires official V3 order and invoice identity on the first durable paid transition.';

COMMENT ON COLUMN legend_commerce.orders.order_number IS
  'Customer-facing LegendMural order number. Format policy is configured by application logic and is intentionally not hardcoded in this migration.';

COMMENT ON TABLE legend_commerce.document_number_series IS
  'Transactional counters for independent official document-number series. Allocation must lock the selected row inside the paid finalization transaction.';

COMMENT ON TABLE legend_commerce.invoices IS
  'Immutable issued-invoice source of truth. Runtime mutation privileges are restricted separately by the V3 grant migration.';

COMMIT;
